name: Lint & Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    # The 'types' field specifies which pull request events will trigger this workflow:
    # - 'opened': when a new pull request is created
    # - 'synchronize': when commits are pushed to an existing pull request (e.g., after pushing new changes)
    # - 'reopened': when a previously closed pull request is reopened
    types: [opened, synchronize, reopened]

jobs:
  ts-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Install dependencies
        # The --frozen-lockfile flag ensures that pnpm will not modify the lockfile during install.
        # This guarantees that the dependencies installed exactly match those specified in pnpm-lock.yaml,
        # helping to prevent unexpected changes or mismatches in CI environments.
        run: pnpm install --frozen-lockfile
      - name: Run Biome Lint
        run: pnpm lint